### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by Chromosone** [ErikBooij/BittrexAPIClient#1]
The script returns the following error:

`Parse error: syntax error, unexpected ':', expecting ';' or '{' in /home/admin/domains/*/public_html/vendor/erikbooij/bittrex-client/src/Client.php on line 61`

This is my script:

`ini_set('display_errors', 1); 
require __DIR__.'/vendor/erikbooij/bittrex-client/src/Client.php';
$bittrexClient = new ErikBooij\Bittrex\Client('', '');

Deleted domain name and API key and secret for privacy reasons.`

**Comment by ErikBooij** [comment]
@Chromosone Thanks for your message. The package was created for PHP 7, it appears you're running PHP 5.X, am I right?

**Comment by Chromosone** [comment]
Yeah 5.5.30. Sorry about that.

**Comment by ErikBooij** [comment]
Don't be, it's good you ran into this. I'll amend the documentation to reflect this requirement.

**Comment by Chromosone** [comment]
Ok, thankyou.

**Comment by Chromosone** [comment]
Sorry to disturb you again, i'm getting a new error. maybe add an example to you're project?

`
Fatal error: Uncaught Error: Class 'GuzzleHttp\Client' not found in /home/onewc/domains/*/public_html/vendor/erikbooij/bittrex-client/src/Client.php:52 Stack trace: #0 /home/onewc/domains/*/public_html/index.php(5): ErikBooij\Bittrex\Client->__construct('f32b45140fa14f3...', '1dde2df7372f438...') #1 {main} thrown in /home/onewc/domains/*/public_html/vendor/erikbooij/bittrex-client/src/Client.php on line 52`
