### ISSUE TITLE
Error in function getRate() while using getOrderBook()

### ISSUE THREAD

**Issue by Chromosone** [ErikBooij/BittrexAPIClient#2]
Getting an error on the folowing piece of code:

`$orders = $bittrexClient->getOrderBook('BTC-LTC');
echo $orders[0]->getRate();`

This is the error: 
`Notice: Undefined offset: 0 in /home/onewc/domains/*/public_html/index.php on line 13
Fatal error: Uncaught Error: Call to a member function getRate() on null in /home/onewc/domains/*/public_html/index.php:13 Stack trace: #0 {main} thrown in /home/onewc/domains/*/public_html/index.php on line 13`

**Comment by ErikBooij** [comment]
The method returns a multidimensional array with orders.

Try 

```php
$orders = $bittrexClient->getOrderBook('BTC-LTC');

echo $orders['buy'][0]->getRate();
// or
echo $orders['sell'][0]->getRate();
```
